<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create(
            'order_addition_submissions',
            function (Blueprint $table): void {
                $table->id();

                $table->foreignId(
                    'order_id'
                )
                    ->constrained('orders')
                    ->cascadeOnDelete();

                /*
                 * Generated by the customer browser.
                 *
                 * A retry must reuse the same UUID.
                 */
                $table->uuid(
                    'client_submission_id'
                )->unique();

                /*
                 * Prevents the same UUID from being reused
                 * with different additional items.
                 */
                $table->char(
                    'submission_hash',
                    64
                );

                $table->timestamps();

                $table->index([
                    'order_id',
                    'created_at',
                ]);
            }
        );
    }

    public function down(): void
    {
        Schema::dropIfExists(
            'order_addition_submissions'
        );
    }
};
